// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240105222340_ChangePriorityToComputerType")]
    partial class ChangePriorityToComputerType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Data.ComputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("GraphicsCard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerType = 1,
                            DateOfManufacture = new DateTime(2018, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GraphicsCard = "GK1",
                            Manufacturer = "Apple",
                            Name = "Nazwa 1",
                            Processor = "Procesor 1",
                            Storage = "512Gb"
                        },
                        new
                        {
                            Id = 2,
                            ComputerType = 3,
                            DateOfManufacture = new DateTime(2021, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GraphicsCard = "GK2",
                            Manufacturer = "Samsung",
                            Name = "Nazwa 2",
                            Processor = "Procesor 2",
                            Storage = "1Tb"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
